# Generated by Django 2.2.6 on 2019-12-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_unlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='unlikes',
        ),
    ]
